---
engines:
  duplication:
    enabled: false
    checks:
      Similar Code:
        enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
      complexity:
        enabled: true
  fixme:
    enabled: false
ratings:
  paths:
    - "**.js"
    - "**.jsx"
exclude_paths:
  - "/node_modules/*"
  - "flow-typed/*"
