---
engines:
  duplication:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
      complexity:
        enabled: true
  fixme:
    enabled: false
ratings:
  paths:
    - "**.js"
    - "**.jsx"
