export const SIGN_IN_FIREBASE = 'sign_in_with_email_and_password'
export const SIGN_UP_SUCCESS = 'sign_up_in_firebase_success'
export const SIGN_UP_FAILED = 'sign_up_in_firebase_failed'
export const SAVE_PROFILE_FIREBASE = 'save_profile'
export const FORGOT_PASSWORD_SUCCESS = 'forgot_password_success'
export const FORGOT_PASSWORD_FAILED = 'forgot_password_failed'
