export const UPDATE_USER = 'update_user'
export const SIGN_UP_SUCCESS = 'sign_up_success'
export const ALERT_AUTH_FAILED = 'authentication_failed'
export const UPDATE_PROFILE = 'update_profile'
export const FORGOT_PASSWORD_SUCCESS = 'forgot_password_success'
